Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-07, with the labels that each got.

#1935 Removed unnecessary worker thread.
  MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs
Labels: enhancement

#1951 Fix Calendar to use ClearType
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml
Labels: enhancement, release notes

#1934 Add TextFieldAssist.PrefixText
  MainDemo.Wpf/ComboBoxes.xaml
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.Wpf/TextFieldAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement, release notes

#1958 Add Prev and Next button for demo app items
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/MainWindow.xaml
Labels: demo app

#1960 Added SnackbarMessageQueue.Clear
  MainDemo.Wpf/Snackbars.xaml
  MainDemo.Wpf/Snackbars.xaml.cs
  MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs
Labels: enhancement

#1961 Change NumericUpDown context menu to MaterialDesignDefaultContextMenu
  MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.NumericUpDown.xaml
Labels: bug, mdix.mahapps

#1962 Fix Toggles section scrollbar issue
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
Labels: demo app

#1968 Fix for "DatePicker with Floating Hint Style's Top Margin/Padding: Issue # 1966
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
Labels: enhancement

#1989 Add MahApps.MaterialDesignPasswordBox
  MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.Defaults.xaml
  MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.PasswordBox.xaml
Labels: enhancement, mdix.mahapps

#1991 Switching to XAMLTest for UI testing
  MaterialDesignThemes.UITests/App.cs
  MaterialDesignThemes.UITests/AppiumHelpers.cs
  MaterialDesignThemes.UITests/DemoApp/DemoAppTests.cs
  MaterialDesignThemes.UITests/DemoApp/MainWindow.cs
  MaterialDesignThemes.UITests/MaterialDesignSpec.cs
  MaterialDesignThemes.UITests/MaterialDesignThemes.UITests.csproj
  MaterialDesignThemes.UITests/Samples/DialogHost/WithCounter.xaml
  MaterialDesignThemes.UITests/Samples/DialogHost/WithCounter.xaml.cs
  MaterialDesignThemes.UITests/TestBase.cs
  MaterialDesignThemes.UITests/TestRecorder.cs
  MaterialDesignThemes.UITests/UITestCases.cs
  MaterialDesignThemes.UITests/UITestCases/MainWindow.cs
  MaterialDesignThemes.UITests/UITestCases/TestCases/DialogHostTests.cs
  MaterialDesignThemes.UITests/WPF/Button/RaisedButtonTests.cs
  MaterialDesignThemes.UITests/WPF/DialogHost/DialogHostTests.cs
  MaterialDesignThemes.UITests/WPF/ListBox/ListBoxTests.cs
  MaterialDesignThemes.UITests/XamlTestMixins.cs
  MaterialDesignThemes.Wpf/MaterialDesignLightTheme.cs
  MaterialDesignToolkit.Full.sln
  UITestCases/App.xaml
  UITestCases/App.xaml.cs
  UITestCases/AssemblyInfo.cs
  UITestCases/ITestCase.cs
  UITestCases/MainWindow.xaml
  UITestCases/MainWindow.xaml.cs
  UITestCases/MainWindowViewModel.cs
  UITestCases/TestCaseNameAttribute.cs
  UITestCases/TestCaseNameConverter.cs
  UITestCases/TestCases/DialogHost/DialogHostOverlay.xaml.cs
  UITestCases/UITestCases.csproj
Labels: enhancement

#1986 [Expander] Rework & Performance Improvements
  MainDemo.Wpf/Expander.xaml
  MaterialDesignThemes.Wpf.Tests/Converters/ExpanderDirectionConverterTests.cs
  MaterialDesignThemes.Wpf/Converters/ExpanderDirectionConverter.cs
  MaterialDesignThemes.Wpf/Converters/ExpanderRotateAngleConverter.cs
  MaterialDesignThemes.Wpf/ExpanderAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Expander.xaml
Labels: release notes, visual breaking change
