Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-06, with the labels that each got.

#1873 Changed colors for outlined button
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml
Labels: enhancement, visual breaking change

#1881 MaterialDesignTabRadioButton disabled style
  MainDemo.Wpf/Toggles.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
Labels: demo app, enhancement

#1884 GetTheme was not populating ToolBackground/ToolForeground
  MaterialDesignThemes.Wpf.Tests/ColorDefinitionsTests.cs
  MaterialDesignThemes.Wpf.Tests/MdixHelper.cs
  MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.cs
Labels: bug, mdix.colors

#1895 Fixes HintAssist.Background for Text- and PasswordBox
  MaterialDesignThemes.Wpf/HintAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement, release notes

#1897 Fixed scrollbar thumb hit-test area
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ScrollBar.xaml
Labels: enhancement

#1902 Cleanup of several XAML warnings.
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.CheckBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToolBar.xaml
Labels: demo app

#1874 Fix thread unsafe code in SnackbarMessageQueue.
  MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs
Labels: enhancement

#1886 ButtonProgressAssist support in MaterialDesignTabRadioButton
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
Labels: enhancement, release notes

#1890 Enabled strong name for WPF projects
  Directory.Build.props
  MahMaterialDragablzMashUp/MahAppsDragablzDemo.csproj
  MainDemo.Wpf/MaterialDesignDemo.csproj
  MaterialDesignColors.Wpf.Tests/MaterialDesignColors.Wpf.Tests.csproj
  MaterialDesignColors.Wpf/MaterialDesignColors.Wpf.csproj
  MaterialDesignThemes.MahApps/MaterialDesignThemes.MahApps.csproj
  MaterialDesignThemes.Wpf.Tests/MaterialDesignThemes.Wpf.Tests.csproj
  MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj
  MaterialDesignThemes.Wpf/Properties/AssemblyInfo.cs
  MaterialDesignToolkit.Wpf.sln
  key.snk
Labels: enhancement, release notes

#1916 Fix mistake in DatePicker used
  MainDemo.Wpf/Pickers.xaml.cs
Labels: demo app

#1915 Add Calendar localization.
  MaterialDesignThemes.Wpf.Tests/CalendarFormatInfoTests.cs
  MaterialDesignThemes.Wpf/CalendarFormatInfo.cs
  MaterialDesignThemes.Wpf/Converters/CalendarYearMonthConverter.cs
  MaterialDesignThemes.Wpf/MaterialDateDisplay.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml
Labels: release notes

#1920 Allow for setting Inherit for the base theme
  MahMaterialDragablzMashUp/App.xaml
  MainDemo.Wpf/App.xaml
  MaterialDesignThemes.MahApps/BaseThemeExtensions.cs
  MaterialDesignThemes.Wpf/Theme.cs
  MaterialDesignThemes.Wpf/ThemeExtensions.cs
Labels: demo app, enhancement, mdix.mahapps, release notes

#1866 WIP: UI Tests
  .editorconfig
  MahMaterialDragablzMashUp/MahAppsDragablzDemo.csproj
  MainDemo.Wpf/App.xaml
  MainDemo.Wpf/MainWindow.xaml
  MainDemo.Wpf/PaletteSelector.xaml
  MaterialDesignColors.Wpf.Tests/MaterialDesignColors.Wpf.Tests.csproj
  MaterialDesignThemes.MahApps.Tests/MaterialDesignThemes.MahApps.Tests.csproj
  MaterialDesignThemes.MahApps.Tests/UnitTest1.cs
  MaterialDesignThemes.MahApps.Tests/paket.references
  MaterialDesignThemes.UITests/App.cs
  MaterialDesignThemes.UITests/AppiumHelpers.cs
  MaterialDesignThemes.UITests/DemoApp/DemoAppTests.cs
  MaterialDesignThemes.UITests/DemoApp/MainWindow.cs
  MaterialDesignThemes.UITests/MaterialDesignThemes.UITests.csproj
  MaterialDesignThemes.UITests/TestBase.cs
  MaterialDesignThemes.UITests/TestRecorder.cs
  MaterialDesignThemes.UITests/UITestCases.cs
  MaterialDesignThemes.UITests/UITestCases/MainWindow.cs
  MaterialDesignThemes.UITests/UITestCases/TestCases/DialogHostTests.cs
  MaterialDesignThemes.Wpf.Tests/MaterialDesignThemes.Wpf.Tests.csproj
  MaterialDesignToolkit.Full.sln
  MaterialDesignToolkit.Wpf.slnf
  UITestCases/App.xaml
  UITestCases/App.xaml.cs
  UITestCases/AssemblyInfo.cs
  UITestCases/ITestCase.cs
  UITestCases/MainWindow.xaml
  UITestCases/MainWindow.xaml.cs
  UITestCases/MainWindowViewModel.cs
  UITestCases/TestCaseNameAttribute.cs
  UITestCases/TestCaseNameConverter.cs
  UITestCases/TestCases/DialogHost/DialogHostOverlay.xaml
  UITestCases/TestCases/DialogHost/DialogHostOverlay.xaml.cs
  UITestCases/UITestCases.csproj
  azure-pipelines.yml
Labels: demo app, enhancement

#1925 UI test pipeline debugging
  MaterialDesignThemes.UITests/TestBase.cs
  MaterialDesignThemes.UITests/TestRecorder.cs
  azure-pipelines.yml
Labels: enhancement

#1923 Update NumericUpDown theme to closer match other fields
  MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.Defaults.xaml
  MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.NumericUpDown.xaml
Labels: enhancement, mdix.mahapps, release notes

#1929 Theme fixes
  MahMaterialDragablzMashUp/PaletteSelector.xaml
  MahMaterialDragablzMashUp/PaletteSelectorViewModel.cs
  MahMaterialDragablzMashUp/paket.references
  MainDemo.Wpf/ColorTool.xaml
  MainDemo.Wpf/ColorToolViewModel.cs
  MainDemo.Wpf/Domain/NotifyPropertyChangedExtension.cs
  MainDemo.Wpf/MainWindow.xaml.cs
  MainDemo.Wpf/PaletteSelector.xaml
  MainDemo.Wpf/PaletteSelectorViewModel.cs
  MainDemo.Wpf/paket.references
  MaterialDesignColors.Wpf.Tests/paket.references
  MaterialDesignColors.Wpf/paket.references
  MaterialDesignThemes.MahApps/MahAppsBundledTheme.cs
  MaterialDesignThemes.MahApps/paket.references
  MaterialDesignThemes.Wpf.Tests/paket.references
  MaterialDesignThemes.Wpf/PaletteHelper.cs
  MaterialDesignThemes.Wpf/Theme.cs
  MaterialDesignThemes.Wpf/ThemeExtensions.cs
  MaterialDesignThemes.Wpf/paket.references
  paket-files/paket.restore.cached
  paket.dependencies
  paket.lock
Labels: demo app
