Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-01, with the labels that each got.

#1594 Limiting issue where the displayed date
  MaterialDesignThemes.Wpf/MaterialDateDisplay.cs
Labels: bug

#1596 Set Default Font Size For Text/Password Box
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement

#1580 Change Outlined Text Fields Hint Style
  MaterialDesignThemes.Wpf/Converters/FontSizeToHintOffsetConverter.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement

#1576 Proposed fix for 1550
  MainDemo.Wpf/Lists.xaml
  MaterialDesignThemes.Wpf/ComboBoxPopup.cs
  MaterialDesignThemes.Wpf/ComboBoxPopupPlacement.cs
  MaterialDesignThemes.Wpf/Converters/FallbackBrushConverter.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
Labels: enhancement, visual breaking change
