Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-05, with the labels that each got.

#1791 Added support for vertical toggle list box
  MainDemo.Wpf/Toggles.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml
Labels: enhancement

#1787 Revised DataGrid-Text-Cell
  MainDemo.Wpf/DataGrids.xaml
  MainDemo.Wpf/DataGrids.xaml.cs
  MainDemo.Wpf/Domain/ListsAndGridsViewModel.cs
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/Domain/SelectableViewModel.cs
  MainDemo.Wpf/Lists.xaml
  MaterialDesignThemes.Wpf/DataGridAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml
Labels: enhancement, release notes

#1793 Bug/1722/popup box inherit font size
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml
Labels: enhancement, visual breaking change

#1796 Improved specs implementation for Snackbar
  MainDemo.Wpf/Snackbars.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Snackbar.xaml
  web/images/screen-snackbars.png
Labels: enhancement, release notes

#1798 attempt at a resolution to MaterialDesignInXAML/MaterialDesignInXamlT…
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/Drawers.xaml
  MaterialDesignThemes.Wpf/DrawerHost.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
Labels: enhancement, release notes

#1807 Added attachable property Background to HintAssist.
  MaterialDesignThemes.Wpf/HintAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement, release notes

#1842 Wrapped borders within AdornerDecorator
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
Labels: release notes

#1845 Update to support latest MahApps
  MaterialDesignThemes.MahApps/BaseThemeExtensions.cs
  MaterialDesignThemes.MahApps/MahAppsBundledTheme.cs
  MaterialDesignThemes.MahApps/MahAppsCustomColorTheme.cs
  MaterialDesignThemes.MahApps/MaterialDesignAssist.cs
  paket-files/paket.restore.cached
  paket.dependencies
  paket.lock
Labels: mdix.mahapps, release notes

#1847 Feature/material design choice chip list box
  MainDemo.Wpf/Chips.xaml
  MaterialDesignThemes.Wpf/Converters/IsDarkConverter.cs
  MaterialDesignThemes.Wpf/ThemeAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.CheckBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
Labels: enhancement, release notes

#1861 Updates to support MahApps 2.0
  MahMaterialDragablzMashUp/Mah.xaml
  MaterialDesignThemes.MahApps.nuspec
  MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.RangeSlider.xaml
  paket-files/paket.restore.cached
  paket.dependencies
  paket.lock
Labels: mdix.mahapps

#1838 Adapted DataGrid to specs
  MainDemo.Wpf/DataGrids.xaml
  MaterialDesignThemes.Wpf/Converters/GridLinesVisibilityBorderToThicknessConverter.cs
  MaterialDesignThemes.Wpf/Converters/RemoveAlphaBrushConverter.cs
  MaterialDesignThemes.Wpf/Converters/TopThicknessConverter.cs
  MaterialDesignThemes.Wpf/DataGridAssist.cs
  MaterialDesignThemes.Wpf/IBaseTheme.cs
  MaterialDesignThemes.Wpf/ITheme.cs
  MaterialDesignThemes.Wpf/MaterialDesignDarkTheme.cs
  MaterialDesignThemes.Wpf/MaterialDesignLightTheme.cs
  MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.cs
  MaterialDesignThemes.Wpf/TextBlockAssist.cs
  MaterialDesignThemes.Wpf/Theme.cs
  MaterialDesignThemes.Wpf/ThemeExtensions.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Dark.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Light.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Thumb.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
  web/images/screen-datagrid.png
Labels: demo app, enhancement, release notes, visual breaking change
