Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-09, with the labels that each got.

#2031 Fix TimePicker issue
  MaterialDesignThemes.UITests/WPF/TimePicker/MaterialDesignTimePicker.cs
  MaterialDesignThemes.UITests/WPF/TimePicker/TimePickerTests.cs
  MaterialDesignThemes.Wpf.Tests/TimePickerUnitTests.cs
  MaterialDesignThemes.Wpf/TimePicker.cs
Labels: release notes

#2041 Removed deprecated resource dictionary keys
  MahMaterialDragablzMashUp/App.xaml
  MainDemo.Wpf/App.xaml
  MainDemo.Wpf/ColorTool.xaml
  MainDemo.Wpf/ComboBoxes.xaml
  MainDemo.Wpf/Home.xaml
  MainDemo.Wpf/Palette.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Amber.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Blue.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Cyan.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.DeepOrange.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.DeepPurple.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Green.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Indigo.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.LightBlue.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.LightGreen.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Orange.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Pink.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Purple.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Red.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Teal.xaml
  MaterialDesignColors.Wpf/Themes/Recommended/Accent/MaterialDesignColor.Yellow.xaml
  MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Badged.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.CheckBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Snackbar.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml
Labels: release notes

#2050 Revise date picker
  MainDemo.Wpf/Pickers.xaml
  MaterialDesignThemes.Wpf/CalendarAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
Labels: release notes

#2029 Add the DialogHost close method.
  MaterialDesignThemes.Wpf.Tests/DialogHostTests.cs
  MaterialDesignThemes.Wpf/DialogHost.cs
  MaterialDesignThemes.Wpf/DialogSession.cs
Labels: enhancement, release notes

#2058 Add TemplateBinding for ClipToBounds to ColorZone
  MainDemo.Wpf/ColorZones.xaml
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
Labels: enhancement

#1963 Fix ComboBox popup location
  MaterialDesignThemes.Wpf/ComboBoxPopup.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/TreeHelper.cs
Labels: evaluation required

#2071 Change scrollbar cursor to arrow
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ScrollViewer.xaml
Labels: enhancement

#2070 Foreground colors should be auto generated when selecting a new primary/secondary color
  MainDemo.Wpf/ColorToolViewModel.cs
  MainDemo.Wpf/PaletteHelperExtensions.cs
Labels: demo app
