Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-10, with the labels that each got.

#2077 Update MaterialDesignTheme.PasswordBox.xaml
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
Labels: breaking change

#2084 Rename outlined Password box style
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
Labels: breaking change

#2085 Renamed ColorHelper to ColorAssist
  MaterialDesignColors.Wpf/ColorManipulation/ColorAssist.cs
Labels: breaking change, mdix.colors

#2088 Prefixed "MaterialDesign" to validation theme resources
  MaterialDesignThemes.Wpf.Tests/ColorDefinitionsTests.cs
  MaterialDesignThemes.Wpf/IBaseTheme.cs
  MaterialDesignThemes.Wpf/MaterialDesignDarkTheme.cs
  MaterialDesignThemes.Wpf/MaterialDesignLightTheme.cs
  MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.cs
  MaterialDesignThemes.Wpf/ThemeExtensions.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.CheckBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Dark.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Light.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml
Labels: breaking change, mdix.colors

#2093 Move TransitionAssist to new root namespace #2081
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ProgressBar.xaml
  MaterialDesignThemes.Wpf/TransitionAssist.cs
Labels: breaking change

#2090 Remove obsolete members
  MaterialDesignThemes.Wpf/Converters/CircularProgressBar/LargeArcConverter.cs
  MaterialDesignThemes.Wpf/DialogClosingEventArgs.cs
  MaterialDesignThemes.Wpf/ExpanderAssist.cs
  MaterialDesignThemes.Wpf/Icon.cs
  MaterialDesignThemes.Wpf/IconType.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Expander.xaml
Labels: breaking change

#2095 Renamed all occurance of MaterialDesignFilledTextFieldTextBox to Mate…
  MainDemo.Wpf/ColorTool.xaml
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.UITests/WPF/TextBox/TextBoxTests.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: breaking change

#2097 Rename outlined text style to remove "TextField"
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.UITests/WPF/TextBox/TextBoxTests.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: breaking change

#2098 Removed the old SecondaryAccent resource with updated resource
  MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.cs
Labels: breaking change

#2105 Fix demo app nav buttons issues
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
Labels: demo app

#2104 Demo App Code Cleanup
  MainDemo.Wpf/Buttons.xaml
  MainDemo.Wpf/Buttons.xaml.cs
  MainDemo.Wpf/Cards.xaml
  MainDemo.Wpf/Cards.xaml.cs
  MainDemo.Wpf/Chips.xaml
  MainDemo.Wpf/Chips.xaml.cs
Labels: demo app

#2106 Auto color correction
  MainDemo.Wpf/App.xaml
  MaterialDesignColors.Wpf.Tests/ColorAssistTests.cs
  MaterialDesignColors.Wpf.Tests/MaterialDesignColors.Wpf.Tests.csproj
  MaterialDesignColors.Wpf/ColorManipulation/ColorAssist.cs
  MaterialDesignThemes.MahApps/MahAppsBundledTheme.cs
  MaterialDesignThemes.MahApps/MahAppsCustomColorTheme.cs
  MaterialDesignThemes.UITests/MaterialDesignThemes.UITests.csproj
  MaterialDesignThemes.UITests/Samples/Theme/ColorAdjustWindow.xaml
  MaterialDesignThemes.UITests/Samples/Theme/ColorAdjustWindow.xaml.cs
  MaterialDesignThemes.UITests/TestBase.cs
  MaterialDesignThemes.UITests/WPF/Theme/ColorAdjustTests.cs
  MaterialDesignThemes.UITests/XamlTestMixins.cs
  MaterialDesignThemes.Wpf.Tests/MaterialDesignThemes.Wpf.Tests.csproj
  MaterialDesignThemes.Wpf/BundledTheme.cs
  MaterialDesignThemes.Wpf/ColorAdjustment.cs
  MaterialDesignThemes.Wpf/ColorSelection.cs
  MaterialDesignThemes.Wpf/Contrast.cs
  MaterialDesignThemes.Wpf/Converters/IsDarkConverter.cs
  MaterialDesignThemes.Wpf/CustomColorTheme.cs
  MaterialDesignThemes.Wpf/PaletteHelper.cs
  MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.cs
  MaterialDesignThemes.Wpf/Theme.cs
  MaterialDesignThemes.Wpf/ThemeExtensions.cs
Labels: enhancement, mdix.colors, release notes

#2113 MaterialDesignDiscreteSlider added tick support
  MainDemo.Wpf/Sliders.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Slider.xaml
Labels: enhancement

#2115 Adding sample in the demo app
  MainDemo.Wpf/Sliders.xaml
Labels: demo app

#2114 Updating ColorZoneModes to new naming of Secondary rather than Accent
  MahMaterialDragablzMashUp/MainWindow.xaml
  MainDemo.Wpf/Buttons.xaml
  MainDemo.Wpf/Cards.xaml
  MainDemo.Wpf/ColorZones.xaml
  MainDemo.Wpf/GroupBoxes.xaml
  MainDemo.Wpf/NavigationRail.xaml
  MainDemo.Wpf/Trees.xaml
  MaterialDesignThemes.UITests/WPF/ColorZone/ColorZoneTests.cs
  MaterialDesignThemes.Wpf/ColorZoneMode.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Badged.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TabControl.xaml
Labels: breaking change, release notes

#2116 Change default ClipToBounds of ColorZone so shadows show by default.
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
Labels: visual breaking change

#2064 add dialog exist method
  MaterialDesignThemes.Wpf.Tests/DialogHostTests.cs
  MaterialDesignThemes.Wpf/DialogHost.cs
Labels: enhancement

#2117 Last of the documented breaking API changes for 4.0.0
  MaterialDesignThemes.Wpf/HintAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DialogHost.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml
Labels: breaking change

#2123 Updated ShowMeTheXAML to version 2.0.0.0 and fixed breaking changes, fix #2119
  MahMaterialDragablzMashUp/Mah.xaml
  MainDemo.Wpf/Buttons.xaml
  MainDemo.Wpf/Cards.xaml
  MainDemo.Wpf/Chips.xaml
  MainDemo.Wpf/ColorZones.xaml
  MainDemo.Wpf/ComboBoxes.xaml
  MainDemo.Wpf/DataGrids.xaml
  MainDemo.Wpf/Dialogs.xaml
  MainDemo.Wpf/Drawers.xaml
  MainDemo.Wpf/Expander.xaml
  MainDemo.Wpf/Fields.xaml
  MainDemo.Wpf/GroupBoxes.xaml
  MainDemo.Wpf/Lists.xaml
  MainDemo.Wpf/MaterialDesignDemo.csproj
  MainDemo.Wpf/MenusAndToolBars.xaml
  MainDemo.Wpf/NavigationRail.xaml
  MainDemo.Wpf/Pickers.xaml
  MainDemo.Wpf/Progress.xaml
  MainDemo.Wpf/RatingBar.xaml
  MainDemo.Wpf/Shadows.xaml
  MainDemo.Wpf/Sliders.xaml
  MainDemo.Wpf/Snackbars.xaml
  MainDemo.Wpf/Toggles.xaml
  MainDemo.Wpf/TransitionsDemo/TransitionsDemoHome.xaml
  MainDemo.Wpf/Trees.xaml
  MainDemo.Wpf/Typography.xaml
  paket-files/paket.restore.cached
  paket.dependencies
  paket.lock
Labels: demo app

#2127 Templatebinding for setting shadowdepth on a flipper card. Fixes #2068
  MainDemo.Wpf/Cards.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Flipper.xaml
Labels: enhancement

#2128 Added HintAssist.FontFamily and using it in relevant templates. Solve…
  MainDemo.Wpf/ComboBoxes.xaml
  MaterialDesignThemes.Wpf/HintAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.SmartHint.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
Labels: enhancement

#2145 made MaterialDesignDemo the default startup project
  MaterialDesignToolkit.Full.sln
Labels: demo app
