Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-04, with the labels that each got.

#1729 added VisualStudioToolsManifest to show controls in Toolbox
  MaterialDesignThemes.Wpf/VisualStudioToolsManifest.xml
  MaterialDesignThemes.nuspec
Labels: enhancement

#1738 Adaptions for JetBrains Rider
  .gitignore
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Chip.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RichTextBox.xaml
Labels: demo app

#1749 Page for ComboBoxes in demo app
  MainDemo.Wpf/ComboBoxes.xaml
  MainDemo.Wpf/ComboBoxes.xaml.cs
  MainDemo.Wpf/Domain/DocumentationLinks.xaml
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/Fields.xaml
  MainDemo.Wpf/Fields.xaml.cs
  MainDemo.Wpf/MaterialDesignDemo.csproj
Labels: demo app

#1742 Fixing compiler warning NETSDK1106 in demo app
  MainDemo.Wpf/MaterialDesignDemo.csproj
Labels: demo app

#1741 Support search for aliases of pack icons
  MainDemo.Wpf/ButtonsViewModel.cs
  MainDemo.Wpf/Converters/StringJoinConverter.cs
  MainDemo.Wpf/Domain/DemoItem.cs
  MainDemo.Wpf/Domain/NotifyPropertyChangedExtension.cs
  MainDemo.Wpf/Domain/TextFieldsViewModel.cs
  MainDemo.Wpf/Domain/TreesViewModel.cs
  MainDemo.Wpf/IconPack.xaml
  MainDemo.Wpf/IconPackViewModel.cs
  MainDemo.Wpf/PackIconKindGroup.cs
Labels: demo app

#1754 Updated screenshots in README for ComboBoxes-Page
  README.md
  web/images/screen-comboboxes.png
  web/images/screen-fields.png
Labels: demo app

#1750 Set Dialog-Task-Result after IsOpen to prevent "DialogHost is already open."
  MaterialDesignThemes.Wpf.Tests/DialogHostTests.cs
  MaterialDesignThemes.Wpf/DialogClosingEventArgs.cs
  MaterialDesignThemes.Wpf/DialogHost.cs
  MaterialDesignThemes.Wpf/DialogSession.cs
Labels: bug

#1759 Added MaterialDesignFilterChip(Outline)CheckBox
  MainDemo.Wpf/Chips.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.CheckBox.xaml
Labels: enhancement, release notes

#1755 Added Snackbar.ActionButtonPlacement to support own line for action button
  MainDemo.Wpf/Snackbars.xaml
  MaterialDesignThemes.Wpf/Converters/SnackbarActionButtonPlacementModeConverter.cs
  MaterialDesignThemes.Wpf/Snackbar.cs
  MaterialDesignThemes.Wpf/SnackbarMessage.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Snackbar.xaml
  README.md
  web/images/screen-snackbars.png
Labels: enhancement, release notes

#1767 Added ValidationAssist.HorizontalAlignment
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml
  MaterialDesignThemes.Wpf/ValidationAssist.cs
Labels: enhancement

#1765 Fixed binding errors in demo app
  MainDemo.Wpf/Domain/BindingProxy.cs
  MainDemo.Wpf/Domain/ListsAndGridsViewModel.cs
  MainDemo.Wpf/Grids.xaml
  MainDemo.Wpf/IconPack.xaml
  MainDemo.Wpf/IconPackViewModel.cs
Labels: demo app

#1763 Fix for MaterialDesignCardGroupBox ColorZone bindings.
  MainDemo.Wpf/GroupBoxes.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.GroupBox.xaml
Labels: enhancement, release notes

#1769 Removed background triggers for MaterialDesignDataGridCell
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml
Labels: visual breaking change

#1777 Added light/dark theme toggle button
  MainDemo.Wpf/MainWindow.xaml
  MainDemo.Wpf/MainWindow.xaml.cs
Labels: demo app
