Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2020-02, with the labels that each got.

#1636 Change hint container from TextBlock to ContentPresenter
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement

#1637 Fix password box underline issue
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
Labels: bug

#1456 Filter Chips
  MainDemo.Wpf/Chips.xaml
  MaterialDesignThemes.Wpf/ListBoxAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml
Labels: enhancement

#1666 Fixing issue with icons differing only by case
  mdresgen/IconDataFactorySyntaxRewriter.cs
  mdresgen/IconThing.cs
Labels: bug, enhancement

#1497 Adding ShowMeTheXaml to MahAppsDragablzDemo
  MahMaterialDragablzMashUp/App.xaml
  MahMaterialDragablzMashUp/App.xaml.cs
  MahMaterialDragablzMashUp/Mah.xaml
  MahMaterialDragablzMashUp/MainWindow.xaml
  MahMaterialDragablzMashUp/MainWindow.xaml.cs
  MahMaterialDragablzMashUp/XamlDisplayEx.cs
  MahMaterialDragablzMashUp/paket.references
  MainDemo.Wpf/MainWindow.xaml
  MainDemo.Wpf/MainWindow.xaml.cs
  MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.Flyout.xaml
Labels: enhancement
