Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2021-02, with the labels that each got.

#2240 Improve duplicate handling
  MainDemo.Wpf/Snackbars.xaml.cs
  MaterialDesignThemes.Wpf.Tests/MaterialDesignThemes.Wpf.Tests.csproj
  MaterialDesignThemes.Wpf.Tests/SnackbarMessageQueueItemTests.cs
  MaterialDesignThemes.Wpf.Tests/SnackbarMessageQueueTests.cs
  MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs
  MaterialDesignThemes.Wpf/SnackbarMessageQueueItem.cs
Labels: breaking change

#2242 Implementing a character counter when MaxLength is set
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.UITests/WPF/TextBox/TextBoxTests.cs
  MaterialDesignThemes.Wpf/TextFieldAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement, release notes

#2244 Slider spec update
  MainDemo.Wpf/App.xaml
  MainDemo.Wpf/Buttons.xaml
  MainDemo.Wpf/Buttons.xaml.cs
  MainDemo.Wpf/ColorTool.xaml
  MainDemo.Wpf/ColorTool.xaml.cs
  MainDemo.Wpf/DataGrids.xaml.cs
  MainDemo.Wpf/Dialogs.xaml
  MainDemo.Wpf/Dialogs.xaml.cs
  MainDemo.Wpf/Domain/ButtonsViewModel.cs
  MainDemo.Wpf/Domain/ColorToolViewModel.cs
  MainDemo.Wpf/Domain/ComboBoxesViewModel.cs
  MainDemo.Wpf/Domain/DemoItem.cs
  MainDemo.Wpf/Domain/DialogsViewModel.cs
  MainDemo.Wpf/Domain/FieldsViewModel.cs
  MainDemo.Wpf/Domain/IconPackViewModel.cs
  MainDemo.Wpf/Domain/ListsAndGridsViewModel.cs
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/Domain/NotifyPropertyChangedExtension.cs
  MainDemo.Wpf/Domain/PaletteSelectorViewModel.cs
  MainDemo.Wpf/Domain/PickersViewModel.cs
  MainDemo.Wpf/Domain/SampleDialogViewModel.cs
  MainDemo.Wpf/Domain/SelectableViewModel.cs
  MainDemo.Wpf/Domain/SlidersViewModel.cs
  MainDemo.Wpf/Domain/TreesViewModel.cs
  MainDemo.Wpf/Domain/ViewModelBase.cs
  MainDemo.Wpf/Fields.xaml
  MainDemo.Wpf/IconPack.xaml
  MainDemo.Wpf/Lists.xaml.cs
  MainDemo.Wpf/PaletteSelector.xaml
  MainDemo.Wpf/PaletteSelector.xaml.cs
  MainDemo.Wpf/Pickers.xaml
  MainDemo.Wpf/Pickers.xaml.cs
  MainDemo.Wpf/PickersViewModel.cs
  MainDemo.Wpf/Sliders.xaml
  MainDemo.Wpf/Sliders.xaml.cs
  MainDemo.Wpf/TransitionsDemo/Slide1_Intro.xaml.cs
  MainDemo.Wpf/Trees.xaml
  MainDemo.Wpf/Trees.xaml.cs
  MaterialDesignThemes.Wpf/Converters/SliderValueLabelPositionConverter.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ColorPicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Slider.xaml
  MaterialDesignToolkit.Full.sln.DotSettings
  web/images/screen-sliders.png
Labels: release notes, visual breaking change

#2245 Added SliderAssist.OnlyShowFocusVisualWhileDragging attached property
  MainDemo.Wpf/Sliders.xaml
  MaterialDesignThemes.Wpf/Converters/BooleanAllConverter.cs
  MaterialDesignThemes.Wpf/Converters/InvertBooleanConverter.cs
  MaterialDesignThemes.Wpf/SliderAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Slider.xaml
Labels: enhancement, release notes

#2251 Fix format exception
  MainDemo.Wpf/Drawers.xaml
  MaterialDesignThemes.Wpf/DrawerHostOpenMode.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
Labels: release notes

#2252 Adding an attached property to hide character counter.
  MaterialDesignThemes.UITests/WPF/TextBox/TextBoxTests.cs
  MaterialDesignThemes.Wpf/TextFieldAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: release notes
