Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2021-06, with the labels that each got.

#2335 Add NavigationListBox Style
  MainDemo.Wpf/MainWindow.xaml
  MaterialDesignThemes.Wpf/ListBoxItemAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml
Labels: enhancement, release notes

#2338 Update to Clock styles to follow spec
  MaterialDesignThemes.Wpf/Clock.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Clock.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Defaults.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
  MaterialDesignThemes.Wpf/TimePicker.cs
Labels: enhancement, release notes, visual breaking change

#2347 Change MouseOver color
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml
Labels: visual breaking change

#2348 Update to NavigationRail
  MainDemo.Wpf/NavigationRail.xaml
  MaterialDesignThemes.Wpf/NavigationRailAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TabControl.xaml
Labels: enhancement

#2353 Slider thumb added foreground template binding
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Slider.xaml
Labels: enhancement

#2356 Update Calendar to specs for more customization
  MaterialDesignThemes.Wpf/CalendarAssist.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml
Labels: enhancement, release notes, visual breaking change
