Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2021-12, with the labels that each got.

#2512 🔳 Add outlined assist/input chips
  MainDemo.Wpf/Chips.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Chip.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Defaults.xaml
Labels: enhancement, release notes

#2524 🪄 Demo app: Rearrange fields
  MainDemo.Wpf/Fields.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: enhancement, demo app

#2532 Bug fix by altering MaterialDesignMenu style resources
  MainDemo.Wpf/MenusAndToolBars.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToolBar.xaml
Labels: release notes

#2536 Navigation bar: Demo page updated
  MainDemo.Wpf/NavigationRail.xaml
Labels: demo app

#2538 TextTrimming WordEllipsis added for MaterialDesignDataGridTextBoxColu…
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml
Labels: enhancement

#2530 🎨 Fix progress bar foreground and background color for outlined and flat buttons
  MainDemo.Wpf/Buttons.xaml
  MaterialDesign3.Demo.Wpf/Buttons.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml
Labels: enhancement, release notes

#2544 Tab control extended
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/Tabs.xaml
  MainDemo.Wpf/Tabs.xaml.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesign2.Defaults.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesign3.Defaults.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Defaults.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TabControl.xaml
Labels: enhancement, release notes
