Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2022-07, with the labels that each got.

#2758 Added UniformCornerRadius to Flipper
  MainDemo.Wpf/Cards.xaml
  MaterialDesignThemes.Wpf/Flipper.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Flipper.xaml
Labels: enhancement, release notes

#2757 Fix2658
  MainDemo.Wpf/Cards.xaml
  MaterialDesignThemes.UITests/WPF/Cards/OutlinedCardTests.cs
  MaterialDesignThemes.UITests/XamlTestMixins.cs
  MaterialDesignThemes.Wpf.Tests/Converters/DoubleToCornerRadiusConverterTests.cs
  MaterialDesignThemes.Wpf/Converters/DoubleToCornerRadiusConverter.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Card.xaml
Labels: enhancement, visual breaking change, release notes

#2767 Added DialogHost.DialogClosed event
  MainDemo.Wpf/Dialogs.xaml
  MainDemo.Wpf/Dialogs.xaml.cs
  MainDemo.Wpf/Domain/DialogsViewModel.cs
  MaterialDesignThemes.Wpf.Tests/DialogHostTests.cs
  MaterialDesignThemes.Wpf/DialogClosedEventArgs.cs
  MaterialDesignThemes.Wpf/DialogClosedEventHandler.cs
  MaterialDesignThemes.Wpf/DialogHost.cs
  MaterialDesignThemes.Wpf/DialogHostEx.cs
Labels: enhancement

#2765 Various changes for cards and shadows
  MainDemo.Wpf/Shadows.xaml
  MaterialDesignThemes.Wpf/Card.cs
  MaterialDesignThemes.Wpf/Converters/ShadowInfo.cs
  MaterialDesignThemes.Wpf/ShadowAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Card.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Shadows.xaml
Labels: visual breaking change, release notes

#2764 Allow "half" rating selection
  MainDemo.Wpf/RatingBar.xaml
  MainDemo.Wpf/RatingBar.xaml.cs
  MaterialDesign3.Demo.Wpf/RatingBar.xaml.cs
  MaterialDesignThemes.Wpf.Tests/RatingBarTests.cs
  MaterialDesignThemes.Wpf/RatingBar.cs
  MaterialDesignThemes.Wpf/RatingBarButton.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RatingBar.xaml
Labels: enhancement, release notes
