Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2022-11, with the labels that each got.

#2932 Refactor PasswordBoxAssist.Password to use behaviors (issue 2930)
  Directory.packages.props
  MaterialDesignThemes.UITests/Samples/PasswordBox/BoundPasswordBox.xaml
  MaterialDesignThemes.UITests/Samples/PasswordBox/BoundPasswordBox.xaml.cs
  MaterialDesignThemes.UITests/Samples/PasswordBox/BoundPasswordBoxViewModel.cs
  MaterialDesignThemes.UITests/Samples/PasswordBox/BoundPasswordBoxWindow.xaml
  MaterialDesignThemes.UITests/Samples/PasswordBox/BoundPasswordBoxWindow.xaml.cs
  MaterialDesignThemes.UITests/WPF/PasswordBoxes/PasswordBoxTests.cs
  MaterialDesignThemes.Wpf/BehaviorCollection.cs
  MaterialDesignThemes.Wpf/Behaviors/PasswordBoxBehavior.cs
  MaterialDesignThemes.Wpf/Behaviors/PasswordBoxRevealTextBoxBehavior.cs
  MaterialDesignThemes.Wpf/BehaviorsAssist.cs
  MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj
  MaterialDesignThemes.Wpf/PasswordBoxAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.nuspec
Labels: enhancement, demo app, release notes

#2961 Update MainWindow.xaml
  MainDemo.Wpf/MainWindow.xaml
Labels: demo app

#2975 Adding .NET7 target
  .editorconfig
  .github/actions/build-and-test/action.yml
  .github/workflows/icon_update.yml
  Directory.Build.props
  MahMaterialDragablzMashUp/MahAppsDragablzDemo.csproj
  MainDemo.Wpf/MaterialDesignDemo.csproj
  MaterialDesign3.Demo.Wpf/MaterialDesign3Demo.csproj
  MaterialDesignColors.Wpf.Tests/MaterialDesignColors.Wpf.Tests.csproj
  MaterialDesignColors.Wpf/MaterialDesignColors.Wpf.csproj
  MaterialDesignColors.nuspec
  MaterialDesignThemes.MahApps.nuspec
  MaterialDesignThemes.MahApps/MaterialDesignThemes.MahApps.csproj
  MaterialDesignThemes.UITests/XamlTestMixins.cs
  MaterialDesignThemes.Wpf.Tests/MaterialDesignThemes.Wpf.Tests.csproj
  MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj
  MaterialDesignThemes.nuspec
  Scripts/BuildNugets.ps1
  global.json
  mdresgen/MdPalette.cs
  mdresgen/Program.cs
  mdresgen/mdresgen.csproj
Labels: release notes

#2977 Allow for resizing the ToggleButton by setting the Width
  MainDemo.Wpf/Toggles.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml
  MaterialDesignThemes.Wpf/ToggleButtonAssist.cs
Labels: enhancement
