Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2022-05, with the labels that each got.

#2662 adding ComboBoxAssist.MaxLength property
  MaterialDesignThemes.Wpf/ComboBoxAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/TreeHelper.cs
Labels: enhancement

#2663 Increasing minimum framework to net462
  MaterialDesignColors.Wpf/MaterialDesignColors.Wpf.csproj
  MaterialDesignColors.nuspec
  MaterialDesignThemes.MahApps.nuspec
  MaterialDesignThemes.MahApps/MaterialDesignThemes.MahApps.csproj
  MaterialDesignThemes.UITests/WPF/DialogHosts/DialogHostTests.cs
  MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj
  MaterialDesignThemes.nuspec
Labels: release notes

#2716 Adding new TimeChanged event to Clock
  MaterialDesignThemes.Wpf.Tests/ClockTests.cs
  MaterialDesignThemes.Wpf/Clock.cs
  MaterialDesignThemes.Wpf/TimeChangedEventArgs.cs
Labels: enhancement, release notes
