Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2023-12, with the labels that each got.

#3403 Adding toggle template selector to popup box
  MaterialDesignThemes.Wpf/PopupBox.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml
Labels: enhancement

#3382 SplitButton leveraging PopupBox
  MainDemo.Wpf/Buttons.xaml
  MaterialDesign3.Demo.Wpf/Buttons.xaml
  MaterialDesignThemes.UITests/Samples/SplitButton/SplitButtonWithCommandBinding.xaml
  MaterialDesignThemes.UITests/Samples/SplitButton/SplitButtonWithCommandBinding.xaml.cs
  MaterialDesignThemes.UITests/Samples/SplitButton/SplitButtonWithCommandBindingWindow.xaml
  MaterialDesignThemes.UITests/Samples/SplitButton/SplitButtonWithCommandBindingWindow.xaml.cs
  MaterialDesignThemes.UITests/TestBase.cs
  MaterialDesignThemes.UITests/WPF/PopupBoxes/PopupBoxTests.cs
  MaterialDesignThemes.UITests/WPF/SplitButtons/SplitButtonTests.cs
  MaterialDesignThemes.Wpf/Converters/CornerRadiusCloneConverter.cs
  MaterialDesignThemes.Wpf/Converters/FirstNonNullConverter.cs
  MaterialDesignThemes.Wpf/PopupBox.cs
  MaterialDesignThemes.Wpf/SplitButton.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.SplitButton.xaml
Labels: release notes

#3414 Add support for TextFieldAssist.HasClearButton in RichTextBox
  MainDemo.Wpf/SmartHint.xaml
  MaterialDesignThemes.Wpf/Internal/ClearText.cs
Labels: enhancement, release notes
