Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2023-05, with the labels that each got.

#3182 Fixing issue with validation template not updating when current error changes
  MaterialDesignThemes.UITests/Samples/Validation/ValidationUpdates.xaml
  MaterialDesignThemes.UITests/Samples/Validation/ValidationUpdates.xaml.cs
  MaterialDesignThemes.UITests/WPF/TextBoxes/TextBoxTests.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml
Labels: bug

#3202 Removed netcoreapp3.1 tfm
  .github/workflows/build_artifacts.yml
  MahMaterialDragablzMashUp/MahAppsDragablzDemo.csproj
  MainDemo.Wpf/MaterialDesignDemo.csproj
  MaterialDesign3.Demo.Wpf/MaterialDesign3Demo.csproj
  MaterialDesignColors.Wpf.Tests/MaterialDesignColors.Wpf.Tests.csproj
  MaterialDesignColors.Wpf/MaterialDesignColors.Wpf.csproj
  MaterialDesignColors.nuspec
  MaterialDesignThemes.MahApps.nuspec
  MaterialDesignThemes.MahApps/MaterialDesignThemes.MahApps.csproj
  MaterialDesignThemes.Wpf.Tests/MaterialDesignThemes.Wpf.Tests.csproj
  MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj
  MaterialDesignThemes.nuspec
Labels: breaking change, .NET

#3217 Refactor GroupBox elevation
  MainDemo.Wpf/GroupBoxes.xaml
  MaterialDesignThemes.Wpf/Converters/IsTransparentBrushConverter.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.GroupBox.xaml
Labels: enhancement, visual breaking change, release notes

#3225 Fix ContentTemplateSelector bindings in DrawerHost template
  MaterialDesignThemes.UITests/WPF/DrawerHosts/DrawerHostTests.cs
  MaterialDesignThemes.Wpf/Themes/Generic.xaml
Labels: enhancement
