Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2023-02, with the labels that each got.

#3074 TextBox: Respect externally set TextBox.Padding in triggers
  MainDemo.Wpf/Domain/SmartHintViewModel.cs
  MainDemo.Wpf/MainWindow.xaml
  MainDemo.Wpf/SmartHint.xaml
  MaterialDesign3.Demo.Wpf/MainWindow.xaml
  MaterialDesignThemes.Wpf/Constants.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
Labels: visual breaking change, release notes

#3080 Adding new Secondary styles which will eventually replace Accent styles
  .github/workflows/build_artifacts.yml
  MainDemo.Wpf/Buttons.xaml
  MainDemo.Wpf/Cards.xaml
  MainDemo.Wpf/Chips.xaml
  MainDemo.Wpf/ColorZones.xaml
  MainDemo.Wpf/Dialogs.xaml
  MainDemo.Wpf/Drawers.xaml
  MainDemo.Wpf/GroupBoxes.xaml
  MainDemo.Wpf/NavigationRail.xaml
  MainDemo.Wpf/Snackbars.xaml
  MainDemo.Wpf/Toggles.xaml
  MainDemo.Wpf/TransitionsDemo/Slide2_Intro.xaml
  MainDemo.Wpf/TransitionsDemo/Slide3_Intro.xaml
  MainDemo.Wpf/TransitionsDemo/Slide4_CombineTransitions.xaml
  MainDemo.Wpf/TransitionsDemo/Slide5_TransitioningContent.xaml
  MainDemo.Wpf/TransitionsDemo/Slide7_MVVM.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesign3.ToggleButton.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.CheckBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml
Labels: enhancement, release notes

#3086 Cleanup: Aligning hint, helper text and validation error based on padding
  MainDemo.Wpf/Domain/SmartHintViewModel.cs
  MainDemo.Wpf/SmartHint.xaml
  MainDemo.Wpf/SmartHint.xaml.cs
  MaterialDesignThemes.UITests/WPF/ComboBoxes/ComboBoxTests.cs
  MaterialDesignThemes.UITests/WPF/DatePickers/DatePickerTests.cs
  MaterialDesignThemes.UITests/WPF/PasswordBoxes/PasswordBoxTests.cs
  MaterialDesignThemes.UITests/WPF/TextBoxes/TextBoxTests.cs
  MaterialDesignThemes.UITests/WPF/TimePickers/TimePickerTests.cs
  MaterialDesignThemes.Wpf/Converters/ThicknessCloneConverter.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml
Labels: visual breaking change, release notes

#3092 Fixes DialogHost visibility on VM disconnect (#3069)
  MaterialDesignThemes.UITests/Samples/DialogHost/LoadAndUnloadControl.xaml
  MaterialDesignThemes.UITests/Samples/DialogHost/LoadAndUnloadControl.xaml.cs
  MaterialDesignThemes.UITests/TestBase.cs
  MaterialDesignThemes.UITests/WPF/DialogHosts/DialogHostTests.cs
  MaterialDesignThemes.Wpf/DialogHost.cs
Labels: release notes

#3103 Add DialogHost.DialogContentUniformCornerRadius
  MainDemo.Wpf/Dialogs.xaml
  MaterialDesignThemes.Wpf/DialogHost.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DialogHost.xaml
Labels: enhancement, release notes
