Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2024-11, with the labels that each got.

#3709 Added Optimizing-WPF-Rendering-Performance.md file to docd
  docs/Optimizing-WPF-Rendering-Performance.md
Labels: wiki

#3661 NumericUpDown control support decimals value, and the value for each increase or decrease can be set.
  Directory.packages.props
  src/MainDemo.Wpf/Domain/MainWindowViewModel.cs
  src/MainDemo.Wpf/NumericUpDown.xaml
  src/MaterialDesignThemes.Wpf/DecimalUpDown.cs
  src/MaterialDesignThemes.Wpf/NumericUpDown.cs
  src/MaterialDesignThemes.Wpf/Themes/Generic.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.NumericUpDown.xaml
  src/MaterialDesignThemes.Wpf/UpDownBase.cs
  src/MaterialDesignThemes.Wpf/VisualStudioToolsManifest.xml
  tests/MaterialDesignThemes.UITests/MaterialDesignThemes.UITests.csproj
  tests/MaterialDesignThemes.UITests/TestBase.cs
  tests/MaterialDesignThemes.UITests/WPF/UpDownControls/DecimalUpDownTests.cs
  tests/MaterialDesignThemes.UITests/WPF/UpDownControls/NumericUpDownTests.cs
Labels: enhancement, release notes

#3707 Fix 3706 - close tab items in demo
  src/MainDemo.Wpf/Domain/TabsViewModel.cs
  src/MainDemo.Wpf/Tabs.xaml
Labels: demo app

#3705 Fix3628 - Slider ToolTip not showing
  src/MaterialDesignThemes.Wpf/SliderAssist.cs
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Slider.xaml
  tests/MaterialDesignThemes.UITests/WPF/TextBoxes/TextBoxTests.cs
Labels: release notes

#3726 RadioButton 添加自定义大小功能
  src/MainDemo.Wpf/Toggles.xaml
  src/MaterialDesign3.Demo.Wpf/Toggles.xaml
  src/MaterialDesignThemes.Wpf/RadioButtonAssist.cs
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RadioButton.xaml
Labels: enhancement, release notes

#3729 DEMO: Use shared ViewModelBase in Demo3
  src/MaterialDesign3.Demo.Wpf/Domain/DemoItem.cs
  src/MaterialDesign3.Demo.Wpf/Domain/DialogsViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/FieldsViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/IconPackViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/ListsAndGridsViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/PaletteSelectorViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/PickersViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/SampleDialogViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/SampleItem.cs
  src/MaterialDesign3.Demo.Wpf/Domain/SelectableViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/SlidersViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/ThemeSettingsViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/TreesViewModel.cs
  src/MaterialDesign3.Demo.Wpf/Domain/ViewModelBase.cs
  src/MaterialDesign3.Demo.Wpf/TransitionsDemo/Slide1_Intro.xaml.cs
Labels: demo app
