Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2024-06, with the labels that each got.

#3589 Fix 3357: Card double padding
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Card.xaml
Labels: bug

#3591 Changed GroupBoxAssist.HeaderPadding to Thickness
  src/MaterialDesignThemes.Wpf/GroupBoxAssist.cs
Labels: release notes

#3175 Pull Request: Adding New Control NumericUpDown Control to Material Design XAML Toolkit
  src/MainDemo.Wpf/Domain/MainWindowViewModel.cs
  src/MainDemo.Wpf/NumericUpDown.xaml
  src/MainDemo.Wpf/NumericUpDown.xaml.cs
  src/MaterialDesignThemes.Wpf/NumericUpDown.cs
  src/MaterialDesignThemes.Wpf/Themes/Generic.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.NumericUpDown.xaml
  tests/MaterialDesignThemes.UITests/TestBase.cs
  tests/MaterialDesignThemes.UITests/WPF/ListBoxes/ListBoxTests.cs
  tests/MaterialDesignThemes.UITests/WPF/NumericUpDowns/NumericUpDownTests.cs
Labels: enhancement, release notes

#3597 Dropped net7.0-windows target framework due to EOL, add net8.0-window…
  MaterialDesignToolkit.Full.sln
  src/MahMaterialDragablzMashUp/MahAppsDragablzDemo.csproj
  src/MainDemo.Wpf/MaterialDesignDemo.csproj
  src/MaterialDesign3.Demo.Wpf/MaterialDesign3Demo.csproj
  src/MaterialDesignColors.Wpf/MaterialDesignColors.Wpf.csproj
  src/MaterialDesignColors.Wpf/MaterialDesignColors.nuspec
  src/MaterialDesignThemes.MahApps/MaterialDesignThemes.MahApps.csproj
  src/MaterialDesignThemes.MahApps/MaterialDesignThemes.MahApps.nuspec
  src/MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj
  src/MaterialDesignThemes.Wpf/MaterialDesignThemes.nuspec
  src/MaterialDesignToolkit.ResourceGeneration/IconDiff.cs
  src/MaterialDesignToolkit.ResourceGeneration/MaterialDesignToolkit.ResourceGeneration.csproj
  tests/MaterialDesignColors.Wpf.Tests/MaterialDesignColors.Wpf.Tests.csproj
  tests/MaterialDesignThemes.UITests/MaterialDesignThemes.UITests.csproj
  tests/MaterialDesignThemes.Wpf.Tests/MaterialDesignThemes.Wpf.Tests.csproj
Labels: release notes

#3616 Fix #3612 - Default value of ShadowAssist.CacheMode set to 'null'
  README.md
  docs/rendering-performance.md
  src/MaterialDesignThemes.Wpf/ShadowAssist.cs
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToolBar.xaml
Labels: release notes

#3615 Align NumericUpDown style with other controls
  src/MainDemo.Wpf/Domain/MainWindowViewModel.cs
  src/MainDemo.Wpf/FieldsLineUp.xaml
  src/MainDemo.Wpf/FieldsLineUp.xaml.cs
  src/MaterialDesign3.Demo.Wpf/FieldsLineUp.xaml
  src/MaterialDesign3.Demo.Wpf/FieldsLineUp.xaml.cs
  src/MaterialDesignThemes.Wpf/DatePickerAssist.cs
  src/MaterialDesignThemes.Wpf/NumericUpDown.cs
  src/MaterialDesignThemes.Wpf/Themes/Generic.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesign2.Defaults.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesign3.Defaults.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.NumericUpDown.xaml
  src/MaterialDesignThemes.Wpf/TimePickerAssist.cs
  tests/MaterialDesignThemes.UITests/WPF/NumericUpDowns/NumericUpDownTests.cs
Labels: enhancement, release notes
