Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2024-02, with the labels that each got.

#3444 The last of the 5.0 cleanup
  MahMaterialDragablzMashUp/App.xaml
  MahMaterialDragablzMashUp/App.xaml.cs
  MainDemo.Wpf/Lists.xaml
  MainDemo.Wpf/MenusAndToolBars.xaml
  MaterialDesignThemes.UITests/WPF/ListBoxes/ListBoxTests.cs
  MaterialDesignThemes.Wpf/Converters/BrushOpacityConverter.cs
  MaterialDesignThemes.Wpf/Converters/BrushRoundConverter.cs
  MaterialDesignThemes.Wpf/ListBoxItemAssist.cs
  MaterialDesignThemes.Wpf/MenuAssist.cs
  MaterialDesignThemes.Wpf/MenuItemAssist.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ObsoleteStyles.xaml
Labels: release notes

#3452 Fix the converter to round the value
  MaterialDesignThemes.Wpf/Converters/FloatingHintTextBlockMarginConverter.cs
Labels: release notes

#3467 Removing defaults in favor of specifying MD2 or MD3
  MaterialDesignThemes.Wpf.Tests/MdixHelper.cs
  MaterialDesignThemes.Wpf.Tests/TextBlockTests.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Defaults.xaml
Labels: breaking change

#3468 Grammatical fixes to App.xaml
  MainDemo.Wpf/App.xaml
Labels: demo app
