Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2024-05, with the labels that each got.

#3552 fix: Remove space in color names
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.BlueGrey.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.BlueGrey.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepOrange.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepOrange.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepOrange.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepPurple.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepPurple.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepPurple.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightGreen.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightGreen.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightGreen.Named.xaml
  src/MaterialDesignToolkit.ResourceGeneration/Program.cs
Labels: breaking change, release notes

#3557 Use CommunityToolkit.Mvvm with Buttons view in demo
  src/MainDemo.Wpf/Domain/ButtonsViewModel.cs
Labels: demo app

#3556 Use recent language features on Demo Convertors
  src/MainDemo.Wpf/Converters/BooleanToDoubleConverter.cs
  src/MainDemo.Wpf/Converters/BrushToHexConverter.cs
  src/MainDemo.Wpf/Converters/ColorToBrushConverter.cs
  src/MainDemo.Wpf/Converters/IsTransparentConverter.cs
  src/MainDemo.Wpf/Converters/MultiValueEqualityConverter.cs
  src/MainDemo.Wpf/Converters/StringJoinConverter.cs
Labels: demo app

#3569 GroupBoxAssist.HeaderPadding
  src/MainDemo.Wpf/GroupBoxes.xaml
  src/MaterialDesignThemes.Wpf/GroupBoxAssist.cs
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.GroupBox.xaml
Labels: visual breaking change

#3566 Use CommunityToolkit.Mvvm with Dialogs view in demo
  src/MainDemo.Wpf/Domain/DialogsViewModel.cs
Labels: demo app

#3575 Fix smart hint resting opacity and (input control) enabled/disabled state
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
Labels: bug

#3580 Removed space in color foreground names
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.BlueGrey.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.BlueGrey.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepOrange.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepOrange.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepOrange.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepPurple.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepPurple.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.DeepPurple.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Named.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightGreen.Named.Primary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightGreen.Named.Secondary.xaml
  src/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightGreen.Named.xaml
Labels: release notes
