Repository MaterialDesignInXAML/MaterialDesignInXamlToolkit, pull requests merged in 2024-04, with the labels that each got.

#2948 Uniform style in demo app pages
  MainDemo.Wpf/App.xaml
  MainDemo.Wpf/Buttons.xaml
  MainDemo.Wpf/Cards.xaml
  MainDemo.Wpf/Chips.xaml
  MainDemo.Wpf/ColorTool.xaml
  MainDemo.Wpf/ColorZones.xaml
  MainDemo.Wpf/ComboBoxes.xaml
  MainDemo.Wpf/DataGrids.xaml
  MainDemo.Wpf/Dialogs.xaml
  MainDemo.Wpf/Domain/DocumentationLinks.xaml
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/Drawers.xaml
  MainDemo.Wpf/Elevation.xaml
  MainDemo.Wpf/Expander.xaml
  MainDemo.Wpf/Fields.xaml
  MainDemo.Wpf/FieldsLineUp.xaml
  MainDemo.Wpf/GroupBoxes.xaml
  MainDemo.Wpf/IconPack.xaml
  MainDemo.Wpf/Lists.xaml
  MainDemo.Wpf/MenusAndToolBars.xaml
  MainDemo.Wpf/NavigationRail.xaml
  MainDemo.Wpf/PaletteSelector.xaml
  MainDemo.Wpf/Pickers.xaml
  MainDemo.Wpf/Progress.xaml
  MainDemo.Wpf/RatingBar.xaml
  MainDemo.Wpf/Sliders.xaml
  MainDemo.Wpf/Snackbars.xaml
  MainDemo.Wpf/Tabs.xaml
  MainDemo.Wpf/Toggles.xaml
  MainDemo.Wpf/Transitions.xaml
  MainDemo.Wpf/TransitionsDemo/TransitionsDemoHome.xaml
  MainDemo.Wpf/Trees.xaml
  MaterialDesign3.Demo.Wpf/Cards.xaml
Labels: enhancement, demo app

#3521 #3333 Modify KeyDown handler to mark event as handled
  MaterialDesignThemes.Wpf/TreeListViewItem.cs
Labels: bug

#3486 Smart hint and text box style refactor
  MainDemo.Wpf/Domain/MainWindowViewModel.cs
  MainDemo.Wpf/Domain/SmartHintViewModel.cs
  MainDemo.Wpf/Properties/launchSettings.json
  MainDemo.Wpf/SmartHint.xaml
  MaterialDesignThemes.UITests/WPF/TextBoxes/TextBoxTests.cs
  MaterialDesignThemes.UITests/WPF/TextFieldDefaultHeightTests.cs
  MaterialDesignThemes.UITests/WPF/Theme/ThemeTests.g.cs
  MaterialDesignThemes.Wpf.Tests/Converters/FloatingHintTransformConverterTests.cs
  MaterialDesignThemes.Wpf/BottomDashedLineAdorner.cs
  MaterialDesignThemes.Wpf/Constants.cs
  MaterialDesignThemes.Wpf/Converters/BooleanToDashStyleConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintContainerMarginConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintInitialHorizontalOffsetConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintInitialVerticalOffsetConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintMarginConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintOffsetCalculationConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintScaleTransformConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintTextBlockMarginConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintTransformConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintTranslateTransformConverter.cs
  MaterialDesignThemes.Wpf/Converters/MathConverter.cs
  MaterialDesignThemes.Wpf/Converters/TextFieldClearButtonVisibilityConverter.cs
  MaterialDesignThemes.Wpf/Converters/TextFieldPrefixTextVisibilityConverter.cs
  MaterialDesignThemes.Wpf/Converters/VerticalAlignmentConverter.cs
  MaterialDesignThemes.Wpf/PrefixSuffixHintBehavior.cs
  MaterialDesignThemes.Wpf/PrefixSuffixVisibility.cs
  MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.g.cs
  MaterialDesignThemes.Wpf/SmartHint.cs
  MaterialDesignThemes.Wpf/TextFieldAssist.cs
  MaterialDesignThemes.Wpf/Theme.g.cs
  MaterialDesignThemes.Wpf/ThemeExtensions.g.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.AutoSuggestBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Dark.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Light.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.SmartHint.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  mdresgen/ThemeColors.json
Labels: enhancement, visual breaking change, release notes

#3540 Post SmartHint adoption cleanup
  MainDemo.Wpf/ComboBoxes.xaml
  MainDemo.Wpf/Domain/SmartHintViewModel.cs
  MainDemo.Wpf/Pickers.xaml
  MaterialDesign3.Demo.Wpf/ComboBoxes.xaml
  MaterialDesignThemes.UITests/WPF/AutoSuggestBoxes/AutoSuggestTextBoxTests.cs
  MaterialDesignThemes.UITests/XamlTestExtensions.cs
  MaterialDesignThemes.Wpf/Constants.cs
  MaterialDesignThemes.Wpf/Converters/DoubleToThicknessConverter.cs
  MaterialDesignThemes.Wpf/Converters/FloatingHintOffsetCalculationConverter.cs
  MaterialDesignThemes.Wpf/Converters/OutlinedDateTimePickerActiveBorderThicknessConverter.cs
  MaterialDesignThemes.Wpf/Converters/OutlinedStyleFloatingHintBackgroundConverter.cs
  MaterialDesignThemes.Wpf/Converters/SizeToRectConverter.cs
  MaterialDesignThemes.Wpf/Converters/TimeToVisibilityConverter.cs
  MaterialDesignThemes.Wpf/Converters/VerticalAlignmentConverter.cs
  MaterialDesignThemes.Wpf/DatePickerAssist.cs
  MaterialDesignThemes.Wpf/HintAssist.cs
  MaterialDesignThemes.Wpf/SmartHint.cs
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.AutoSuggestBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.RichTextBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml
  MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TimePicker.xaml
  MaterialDesignThemes.Wpf/TimePickerAssist.cs
Labels: release notes
